apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Maven Package
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - name: checkout
        uses: cloudbees-io/checkout@v1
      - name: package
        run: |
          ./mvnw package
        uses: docker://eclipse-temurin:21-jdk
        shell: sh
